// <auto-generated />
namespace personal_inforamtion_system_new.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class personlandaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(personlandaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "202108090737245_personlandaddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
